[package]
name = "Xerox-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.16"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4.0", features = ["derive"] }
rayon = "1.10.0"

